#pragma once

#include <cstring>
#include <filesystem>
#include <iomanip>
#include <memory>
#include <optional>
#include <set>
#include <string>
#include <utility>
#include <vector>

#include "graphics/complete.h"
#include "input/complete.h"
#include "interface/gui.h"
#include "interface/window.h"
#include "macros/adjust.h"
#include "meta/misc.h"
#include "program/entry_point.h"
#include "program/errors.h"
#include "program/exit.h"
#include "program/platform.h"
#include "reflection/full_with_poly.h"
#include "stream/readonly_data.h"
#include "strings/common.h"
#include "strings/format.h"
#include "utils/clock.h"
#include "utils/mat.h"
#include "utils/poly_storage.h"
#include "utils/shared_library.h"
#include "utils/unicode.h"
